language: smalltalk
sudo: required
dist: trusty

os:
- linux

smalltalk:
  - Pharo-6.0
  - Pharo-5.0
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "scripts/before_install.sh"
before_script:
  - "scripts/launchSelenium.sh"